### ISSUE TITLE
Taskbar Icon Missing in KDE Plasma Unless Run with Sudo

### ISSUE THREAD

**Issue by bellpepper** [andrebrait/prime-indicator#23]
This seems similar to #7, but opened a new issue anyways.

I was having issues getting the icon to display in the taskbar of Plasma, and noticed that if I run prime-indicator as root, the issue goes away. Here is what I see as my normal user:

```
cd /usr/lib/prime-indicator
./prime-indicator
```
![as-my-user](https://cloud.githubusercontent.com/assets/7130316/20653964/6dee6b2c-b4c9-11e6-89d5-e1d86c1d8982.png)
Notice the missing icon below the "ph" of "Graphics"

But it looks better when I ran it with sudo:
`sudo ./prime-indicator`
![as-root](https://cloud.githubusercontent.com/assets/7130316/20653979/8995ab6a-b4c9-11e6-8355-78f598afdf63.png)

My prime-indicator.cfg:
```
[PowerManagement]
enabled = true
   
[Appearance]
#iconset = theme-default
#iconset = color
iconset = custom(#ffffff)
```
About my system:
```
$ uname -a
Linux ed-Lenovo-Y50-70 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS            (Actually is Kubuntu)
Release:        16.04
Codename:       xenial

$ plasmashell --version
plasmashell 5.6.5
```

Great tool, btw!

**Comment by andrebrait** [comment]
This is weird. I run KDE too. Is it affected no matter which option you set in the config file?

Can you send me the output of `ls -lha /usr/lib/prime-indicator/icons`?

**Comment by bellpepper** [comment]
Any option in the config file will affect the toast (I don't know the proper name) icon properly. For example, here is `iconset = color`:

![color](https://cloud.githubusercontent.com/assets/7130316/20678949/9bf85a26-b54d-11e6-8d36-1a530590c546.png)

```
$ ls -lha /usr/lib/prime-indicator/icons
total 24K
drwxr-xr-x 2 root root 4.0K Nov 21 15:00 .
drwxr-xr-x 3 root root 4.0K Nov 27 17:34 ..
-rw-r--r-- 1 root root 3.9K Nov 21 15:00 prime-indicator-intel.svg
-rw-r--r-- 1 root root 3.9K Nov 21 15:00 prime-indicator-intel-symbolic.svg
-rw-r--r-- 1 root root 3.0K Nov 21 15:00 prime-indicator-nvidia.svg
-rw-r--r-- 1 root root 3.0K Nov 21 15:00 prime-indicator-nvidia-symbolic.svg
```

**Comment by andrebrait** [comment]
That's very, very weird. I'm going to check if the solution to KDE >= 5.8 caused this. If that's the case, I'll have to include a conditional check to see if the user is running KDE with version lesser or greater than 5.8.

**Comment by bellpepper** [comment]
Also, I found a downside to running it with sudo: I cannot interact with the menu icon from the taskbar UI. If I right-click the icon, no menu appears. I have to quit prime-indicator using a kill command.

**Comment by andrebrait** [comment]
Given how the AppIndicator library is unstable with anything other than Ubuntu's Unity, it's not surprising.

A while ago it was reported to me some situations that would cause Gedit to crash when the indicator started, but only if the user had opened it through the GUI by opening a file with a file browser (such as Nautilus, Dolphin, etc.). That's how buggy the AppIndicator library can be.

I'm considering moving it to Qt, since it works well with most desktops.

**Comment by bellpepper** [comment]
You know, I think this must be a local issue. I've began using another application that attempts to display on the taskbar, and it is not displaying properly. The "proper" icon here should be a red logo, but instead it is just a red box. So, I think this issue could be closed as EUE. Something must be wrong on my machine. Sorry if this resulted in chasing a bug that didn't exist.

![image](https://cloud.githubusercontent.com/assets/7130316/20994325/99653e2e-bca4-11e6-8d57-ce9bf3583191.png)

**Comment by andrebrait** [comment]
No problem at all! I haven't had any time to look into the issue anyway. Thank you for providing the information.
