### ISSUE TITLE
There isn't a clear way to remove the indicator.

### ISSUE THREAD

**Issue by Maccer1** [andrebrait/prime-indicator#24]
I want to remove it because my system already does everything I need by default (and I don't really switch between cards). So what files do I need to remove to uninstall it?

**Comment by andrebrait** [comment]
How did you install it? 

If you did it using a packaged version (like the one in webupd8's ppa) ysing dnf, yum or apt, you should uninstall the package.

If you downloaded it from here, there's a uninstall script named uninstall.sh. Just run it as super user, like

`sudo bash uninstall.sh`

**Comment by Maccer1** [comment]
Oops. Sorry, I should have checked that.

**Comment by andrebrait** [comment]
No problem. I didn't include explanations in the README after all.
