### ISSUE TITLE
Doesn't show icons on kubuntu plasma desktop

### ISSUE THREAD

**Issue by cosmicog** [andrebrait/prime-indicator#25]
Screenshot:
![screenshot_20170319_023843](https://cloud.githubusercontent.com/assets/9158844/24076887/523cd142-0c45-11e7-9d2c-2110d931800b.png)
I'm using kubuntu 16.04 with plasmashell 5.5.5.
I'm using `numix-square` theme and I've tried different setting in `prime-indicator.cfg` but same issue hapens with all of it.

**Comment by andrebrait** [comment]
Hi there!

I'm sorry for responding 6 days after you reported the issue. I've been very busy.

It's strange, since I developed it when running Kubuntu, mostly.
What settings did you try?
Can you send me your prime-indicador.cfg?

**Comment by cosmicog** [comment]
Hi, not a problem :)
Sure, I guess that was last try:
```
[PowerManagement]
enabled = true

[Appearance]
iconset = custom(#DFDBD2)
```

**Comment by andrebrait** [comment]
I'll be looking into it.

Weird, as the custom option should force the color. Can you try the "color" option? Does it result in the same?

**Comment by cosmicog** [comment]
Sorry, I'm responding late too. 
Changing configuration works with tooltip. I've changed to `color` and here is result.
![prime-inidcator](https://cloud.githubusercontent.com/assets/9158844/24350116/bb6202fa-12e9-11e7-95f5-f34ba1a95d68.png)
Maybe, It's just my computer's problem?

**Comment by andrebrait** [comment]
May be, but it's more probably something with Plasma 5.5. I remember I developed it when I was in Plasma 5.6, which you can find in the kubuntu-backports repository.

If it's not too much trouble, maybe installing 5.6 will fix it.

My guess is that there's something affecting Plasma when it comes to rendering SVG icons.

**Comment by cosmicog** [comment]
I'm downloading KDE Neon now :D If it works with neon, I'll close this issue because it is related to old version of plasma.

**Comment by andrebrait** [comment]
Great!

AFAIK it works with Neon, as I remember some users reporting it did.
