### ISSUE TITLE
Icon color and size

### ISSUE THREAD

**Issue by poVoq** [andrebrait/prime-indicator#3]
Minor issue only, but on the default menu-bar color of KDE the gray icons are barely visible (darker gray on light gray). Somehow I would prefer a nice Nvidia green or at least full black or something like that.

It also seems like both logos are slightly squeezed horizontally in KDE (the icon displayed seems quadratic, but the actual .svg is a bit rectangular)

**Comment by andrebrait** [comment]
@poVoq Try one of the new icon options I've included and see if you like them =). I've played with them a bit and liked them myself (The new README provides information on the options available)

**Comment by andrebrait** [comment]
I fixed both in commits 1f6e789669562dc646b918db04b85f1f58ccca63 and 93ea9d552460bd41f20b6c20182eb10be5348d1c. I'll report when I merge those to master.

**Comment by andrebrait** [comment]
Just merged. You can now download the code and test it. Check the new custom option for icon color I've included (the README.md file contains details on how to use it). It might be useful to you.

Once you test it and the problems are gone, please report back and/or close the issue as solved!

**Comment by poVoq** [comment]
seems to work great. Thanks!
