### ISSUE TITLE
Icons not shown in KDE

### ISSUE THREAD

**Issue by jsalatas** [andrebrait/prime-indicator#7]
I'm using KDE neon (plasma 5.8.2) and the icon isn't shown in systray.

**Comment by andrebrait** [comment]
Hello @jsalatas. Can you give me some other information? What version of which distro are you using? What method did you use to install it (PPA or the setup script included in this repository)?

**Comment by jsalatas** [comment]
I'm using KDE neon user edition (https://neon.kde.org/)

I installed it using the ppa:nilarimogard/webupd8  as described here 
http://www.webupd8.org/2016/10/prime-indicator-plus-makes-it-easy-to.html

Also in my ~/.config/prime-indicator/prime-indicator.cfg I tried both iconset = color and  iconset = theme-default but none of them worked. 

Thanks for your quick response!!!

**Comment by andrebrait** [comment]
You're welcome. I receive notifications whenever someone opens a issue, so it doesn't take me much time to notice this hahaha.

Can you run it manually in the terminal, copy any output that appears and paste it here?

To do so, run

$ `/usr/lib/prime-indicator/prime-indicator` as your regular user

**Comment by jsalatas** [comment]
Running it from a terminal doesn't produce any output. However I get some errors in plasma's output

Having 

iconset = color 

I get 

Registering ":1.134/org/ayatana/NotificationItem/PRIME_Indicator"
QQuickItem::stackAfter: Cannot stack after 0x5cf9b80, which must be a sibling

Having any of the other three options 

iconset = theme-default 

iconset = symbolic

color(#ffffff)

I get the same message

kde.systemtray: Wrong IconThemePath "/home/john/.config/prime-indicator/icons-symbolic" : too short or does not end with 'icons'

**Comment by andrebrait** [comment]
I see. They must have implemented this check in newer versions. I'll fix the path but I'll also check with the KDE devs if this should really be happening.

On a small note, the correct option for white icons would be `custom(#ffffff)`, not `color(#ffffff)`.

**Comment by andrebrait** [comment]
Out of curiosity, how did you get the output from plasma? System logs? Although I like KDE a lot, I'm not as experienced with it as I am with GNOME. I'm planning on starting to contribute to KDE, so it would be good to know where I'd get such error messages.

**Comment by jsalatas** [comment]
if you run the following commands in a terminal 

killall plasmashell
kstart plasmashell

it will restart plasma and it will give you the terminal prompt back. However in the terminal you run it, it will output some logs

**Comment by andrebrait** [comment]
Wow. Useful.

Commit a4fe029125884fe8f529f6c8c80b4338e6d76ca2 should have fixed this sittuation. Please replace the file in your installation (`/usr/lib/prime-indicator/prime-indicator`) with [the one in this repository](https://github.com/andrebrait/prime-indicator/blob/master/usr/lib/prime-indicator/prime-indicator)

**Comment by jsalatas** [comment]
That didn't work :(

Now whatever I put in iconset I get 

Registering ":1.164/org/ayatana/NotificationItem/PRIME_Indicator"
QQuickItem::stackAfter: Cannot stack after 0x5cf9b80, which must be a sibling

**Comment by andrebrait** [comment]
@jsalatas can you please test it using the script as of commit a5ff3c5f34bbbccf225e41e8bd29384559d862fb ?

**Comment by jsalatas** [comment]
It works! 

Tested with all four options for iconset

**Comment by andrebrait** [comment]
I'm very happy to hear (read) that!

Have you tested switching between cards, etc?

I closed your pull request since commit a5ff3c5f34bbbccf225e41e8bd29384559d862fb fixed the issue. Thanks a lot, since your solution ended up serving as base to the one I made.

**Comment by jsalatas** [comment]
Yes! Switching and everything works. 

Thanks for your effort! :smile:

**Comment by andrebrait** [comment]
Great! I'm closing the issue then. Thanks a lot, too! ;)
